### ISSUE TITLE
Changing cities and location

### ISSUE THREAD

**Issue by rrr-iob** [bennokress/Scriptable-Scripts#2]
Thanks for the amazing widget. 

I am sorry that I don’t get it, but could you please provide instructions how to setup different cities or districts that will then be displayed in the widget?

best regards

**Comment by bennokress** [comment]
Of course! I know it's not as straightforward as other scripts, because those are my first widgets and I primarily made them for my wife and me where customization isn't necessary. It should however be fairly easy to accomplish. All you have to do is change the values provided in the Configuration part of the script which is found below the second "headline" after `Debug`. Depending on the widget you choose there are more or less configuration options and the global dashboard has them all. 

So for the global vaccination and incidence you should adjust the countries to have the correct [ISO-3166 Alpha-3 Code](https://www.wikiwand.com/en/List_of_ISO_3166_country_codes). If you can live with it, it's best to leave the internal names ("germany", "canada" and "usa") as they are or otherwise you would have to do a case sensitive search and replace throughout the whole script. For `flag` use the country codes you entered in `country` and replace the flag emojis:

```
// Global Configuration ////////////////////////
let country = {
    germany: "DEU",
    canada: "CAN",
    usa: "USA"
}

let flag = {
    "DEU": "🇩🇪",
    "CAN": "🇨🇦",
    "USA": "🇺🇸"
}
```

For the local vaccination and incidence I would suggest to use the license plate identification of your desired regions in `location` and again leave the names ("kissing", …) as they are or do a case sensitive search and replace throughout the whole script. Use the identifiers you set in `location` as keys in `coordinates` and `name`. Secondly you need to make sure that the `coordinates` are correct, because those are the ones used for the RKI API. Lastly enter the names of the regions as you would like them to be displayed in the widget in `name`:

```
// Local Configuration /////////////////////////
let location = {
    kissing: "FDB",
    augsburg: "A",
    munich: "M",
    freilassing: "BGL"
}

let coordinates = {
    "FDB": "48.294,10.969",
    "A": "48.366,10.898",
    "M": "48.135,11.613",
    "BGL": "47.835,12.970" 
}

let name = {
    "FDB": "Kissing",
    "A": "Augsburg",
    "M": "München",
    "BGL": "Freilassing"
}
```

That's it. Let me know if you have any problems 😉

**Comment by bennokress** [comment]
I'm closing this now. @rrr-iob please let me know if you have any problems after changing the locations in your fork.
